version: '3.8'

services:
  # database
  hahn-software-db:
    image: postgres:13
    container_name: hahn-software-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=employee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=idrissaithadou@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-data:
  pgadmin-data: